<?php
/**
 * Created by PhpStorm.
 * User: hsedi
 * Date: 1/23/2019
 * Time: 6:46 PM
 */


use Restserver\Libraries\REST_Controller;

defined('BASEPATH') OR exit('No direct script access allowed');

require APPPATH . 'libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';

class RestApi extends REST_Controller
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('WishListModel');
        $this->load->model('UserModel');
    }

    public function index_get()
    {

    }

    public function itemList_get()
    {
        $wishlistDetails = $this->WishListModel->findWishList($this->session->userdata('user_name'));
        //$wisListName = $wishlistDetails['list_name'];
        //$wisListDescription = $wishlistDetails['list_description'];

        $itemList = $this->WishListModel->getAllItems($wishlistDetails->id);

        $this->response($itemList, REST_Controller::HTTP_OK);
    }

    public function itemList_post()
    {

        // $isInserted = $this->ItemListModel->insertItem($this->post('list_name'), $this->post('list_description'), $owner);
        $wishlistDetails = $this->WishListModel->findWishList($this->session->userdata('user_name'));

        $userData = array(
            'id' => '',
            'item_name' => $this->post('item_name'),
            'item_description' => $this->post('item_description'),
            'item_url' => $this->post('item_url'),
            'item_price' => $this->post('item_price'),
            'item_priority' => $this->post('item_priority'),
            'parent_wish_list_id' => $wishlistDetails->id
        );

        $isInserted = $this->WishListModel->insertItem($userData);


        if ($isInserted) {

            $message = [
                'id' => $this->post('id'), // Automatically generated by the model
                'name' => $this->post('list_name'),
                'email' => $this->post('list_description'),
                'status' => 'success',
                'message' => 'Item added'
            ];

            $this->response($message, REST_Controller::HTTP_OK);
        }

        $this->response(['status' => 'failed'], REST_Controller::HTTP_NOT_FOUND);
    }

    public function itemList_put()
    {

        $isUpdated = $this->WishListModel->updateItems($this->put());

        if ($isUpdated) {
            $message = [
                'id' => $this->post('id'), // Automatically generated by the model
                'name' => $this->post('list_name'),
                'email' => $this->post('list_description'),
                'status' => 'success',
                'message' => 'Item added',
                'user_name' => $this->session->userdata('user_name')
            ];

            $this->response($message, REST_Controller::HTTP_OK);
        }
        $this->response(['status' => 'failed'], REST_Controller::HTTP_NOT_FOUND);
    }

    public function itemList_delete($id)
    {
        $isDeleted = $this->WishListModel->deleteItems($id);

        if ($isDeleted) {
            /*$message = [
                'id' => $this->delete('id'), // Automatically generated by the model
                'name' => $this->delete('list_name'),
                'email' => $this->delete('list_description'),
                'status' => 'success',
                'message' => 'Item added'
            ];*/

            $this->response($id, REST_Controller::HTTP_OK);
        }
        $this->response(['status' => 'failed'], REST_Controller::HTTP_NOT_FOUND);
    }

    public function wishlist_post()
    {

        $userData = array(
            'id' => '',
            'user_name' => $this->post('user_name'),
            'user_password' => $this->post('user_password')
        );

        if (!($this->UserModel->insertUser($userData))) {
            $this->response(REST_Controller::HTTP_NOT_FOUND);
        }

        $wishListData = array(
            'id' => '',
            'list_name' => $this->post('list_name'),
            'list_description' => $this->post('list_description'),
            'list_owner' => $this->post('user_name'),
        );

        if (!($this->WishListModel->insertWishList($wishListData))) {
            $this->response(REST_Controller::HTTP_NOT_FOUND);
        }

        $this->response(REST_Controller::HTTP_OK);

    }

    public function wishlist_get()
    {
        $wishListData = $this->WishListModel->getWishList($this->session->userdata('user_name'));
        $this->response($wishListData, REST_Controller::HTTP_OK);
    }

}